export const FETCH_LOGIN_REQUEST = "FETCH_LOGIN_REQUEST";
export const FETCH_LOGIN_SUCCESS = "FETCH_LOGIN_SUCCESS";
export const FETCH_LOGIN_FAILED = "FETCH_LOGIN_FAILED";

export const FETCH_REGISTER_REQUEST = "FETCH_REGISTER_REQUEST";
export const FETCH_REGISTER_SUCESS = "FETCH_REGISTER_SUCESS";
export const FETCH_REGISTER_FAILED = "FETCH_REGISTER_FAILED";


// vaccine Action

export const FETCH_VACCINE_REQUEST = "FETCH_VACCINE_REQUEST";
export const FETCH_VACCINE_SUCESS = "FETCH_VACCINE_SUCESS";
export const FETCH_VACCINE_FAILED = "FETCH_VACCINE_FAILED";

export const FETCH_VACCINE_MONTHID_REQUEST = "FETCH_VACCINE_MONTHID_REQUEST";
export const FETCH_VACCINE_MONTHID_SUCESS = "FETCH_VACCINE_MONTHID_SUCESS";
export const FETCH_VACCINE_MONTHID_FAILED = "FETCH_VACCINE_MONTHID_FAILED";

// pass vaccine name required taken to tab js page.

export const SEND_VACCINE_DATA = "SEND_VACCINE_DATA";

export const SEND_VACCINE_TAKEN = "SEND_VACCINE_TAKEN"